//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCRepoClientApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UCRepoClientApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EmptyUCRepo {
            get {
                object obj = ResourceManager.GetObject("EmptyUCRepo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;?altova_samplexml file:///E:/DriveE/_project/EPRI/C18322-EPRIUseCaseRepository/Source/FilledInTemplates/IEC_UseCaseTemplateExampleGreenButton_TIDY.xml?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xsi:schemaLocation=&quot;http://www.w3.org/1999/xhtml xhtml1-transitional.dtd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EUToIntermediate {
            get {
                return ResourceManager.GetString("EUToIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1252&quot;?&gt;
        ///&lt;xmi:XMI xmi:version=&quot;2.1&quot; xmlns:uml=&quot;http://schema.omg.org/spec/UML/2.1&quot; xmlns:xmi=&quot;http://schema.omg.org/spec/XMI/2.1&quot; xmlns:thecustomprofile=&quot;http://www.sparxsystems.com/profiles/thecustomprofile/1.0&quot; xmlns:EAUML=&quot;http://www.sparxsystems.com/profiles/EAUML/1.0&quot;&gt;
        ///	&lt;xmi:Documentation exporter=&quot;Enterprise Architect&quot; exporterVersion=&quot;6.5&quot;/&gt;
        ///	&lt;uml:Model xmi:type=&quot;uml:Model&quot; name=&quot;EA_Model&quot; visibility=&quot;public&quot;&gt;
        ///		&lt;packagedElement xmi:type=&quot;uml:Package&quot; xmi:id=&quot;EAPK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExchangeProfileXMI {
            get {
                return ResourceManager.GetString("ExchangeProfileXMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IEC_UseCaseTemplate {
            get {
                object obj = ResourceManager.GetObject("IEC_UseCaseTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IEC_UseCaseTemplateGOOD {
            get {
                object obj = ResourceManager.GetObject("IEC_UseCaseTemplateGOOD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IEC62559_UseCaseTemplate {
            get {
                object obj = ResourceManager.GetObject("IEC62559_UseCaseTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2012 sp1 (x64) (http://www.altova.com) by Ronald Pasquarelli (private) --&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:UC=&quot;http://www.TC8.org/IEC62559/UseCaseTemplate/V01&quot; targetNamespace=&quot;http://www.TC8.org/IEC62559/UseCaseTemplate/V01&quot;&gt;
        ///	&lt;xsd:complexType name=&quot;Actor&quot;&gt;
        ///		&lt;xsd:sequence&gt;
        ///			&lt;xsd:element name=&quot;description&quot; type=&quot;xsd:string&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot;/&gt;
        ///			&lt;xsd:element name=&quot;furtherInformation&quot; type=&quot;xsd:s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IEC62559UseCaseTemplate_V01 {
            get {
                return ResourceManager.GetString("IEC62559UseCaseTemplate_V01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;?altova_samplexml file:///E:/DriveE/_project/EPRI/C18322-EPRIUseCaseRepository/Source/FilledInTemplates/TestOut_MODEL.xml?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; exclude-result-prefixes=&quot;xhtml xsi UC&quot; xmlns:UC=&quot;http://www.TC8.org/IEC62559/UseCaseTemplate/V01&quot;
        /// xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///  xsi:schemaLocation=&quot;http://www.w3.org/1999/xhtml xhtml1-transitional.dtd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instanc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntermediateToXHTML {
            get {
                return ResourceManager.GetString("IntermediateToXHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LinkToTest1 {
            get {
                object obj = ResourceManager.GetObject("LinkToTest1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to del UCRepo.eap
        ///copy EmptyUCRepo.eap UCRepo.eap.
        /// </summary>
        internal static string RestoreEmpytEAP {
            get {
                return ResourceManager.GetString("RestoreEmpytEAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UCRepo {
            get {
                object obj = ResourceManager.GetObject("UCRepo", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
